[package]
name = "mock_cktestbtc_minter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.13"
ic-cdk-macros = "0.9"
serde = "1.0"
sha2 = "0.10"
hex = "0.4"

[dev-dependencies]
ic-cdk-macros = "0.9"